import type { DesignTemplateCategory, TemplateLayout } from '@spectra/contracts';

/**
 * Built-in templates (ADR-0040). Code-defined, versioned, read-only; a
 * workspace copies one to edit it. Every layout uses brand colour roles and
 * brand placeholders, so the same template renders on-brand for any brand kit.
 */

export interface BuiltInTemplate {
  key: string;
  version: number;
  name: string;
  description: string;
  category: DesignTemplateCategory;
  formats: string[];
  defaultFormat: string;
  layout: TemplateLayout;
}

const brand = (role: 'primary' | 'secondary' | 'accent' | 'background' | 'text') => ({
  brand: role,
});
const hex = (value: string) => ({ hex: value });

export const BUILT_IN_TEMPLATES: readonly BuiltInTemplate[] = [
  {
    key: 'quote-card',
    version: 1,
    name: 'Quote card',
    description: 'A large quote on the brand colour with attribution and the logo.',
    category: 'QUOTE',
    formats: ['INSTAGRAM_SQUARE', 'INSTAGRAM_PORTRAIT', 'LINKEDIN_POST', 'X_POST'],
    defaultFormat: 'INSTAGRAM_SQUARE',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'quote',
          label: 'Quote',
          kind: 'TEXT',
          required: true,
          maxLength: 280,
          defaultValue: null,
          help: null,
        },
        {
          key: 'attribution',
          label: 'Attribution',
          kind: 'TEXT',
          required: false,
          maxLength: 80,
          defaultValue: '— {{brand.name}}',
          help: null,
        },
      ],
      pages: [
        {
          id: 'page1',
          background: { fill: brand('primary'), imageSlot: null },
          layers: [
            {
              type: 'rect',
              id: 'accentBar',
              box: { x: 0.08, y: 0.1, w: 0.12, h: 0.012 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0.5,
            },
            {
              type: 'text',
              id: 'quoteText',
              box: { x: 0.08, y: 0.16, w: 0.84, h: 0.56 },
              field: 'quote',
              font: 'heading',
              sizeRatio: 0.06,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            {
              type: 'text',
              id: 'attributionText',
              box: { x: 0.08, y: 0.76, w: 0.6, h: 0.08 },
              field: 'attribution',
              font: 'body',
              sizeRatio: 0.032,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'normal',
              autofit: false,
            },
            { type: 'logo', id: 'logo', box: { x: 0.74, y: 0.8, w: 0.18, h: 0.12 } },
          ],
        },
      ],
    },
  },
  {
    key: 'announcement',
    version: 1,
    name: 'Announcement',
    description:
      'A hero photo with a darkened band, headline, supporting line and a call to action.',
    category: 'SOCIAL_POST',
    formats: ['INSTAGRAM_SQUARE', 'INSTAGRAM_PORTRAIT', 'FACEBOOK_POST', 'LINKEDIN_POST', 'X_POST'],
    defaultFormat: 'INSTAGRAM_PORTRAIT',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'photo',
          label: 'Photo',
          kind: 'IMAGE',
          required: false,
          maxLength: 280,
          defaultValue: null,
          help: 'Fills the background; the brand colour shows when empty.',
        },
        {
          key: 'headline',
          label: 'Headline',
          kind: 'TEXT',
          required: true,
          maxLength: 90,
          defaultValue: null,
          help: null,
        },
        {
          key: 'subline',
          label: 'Supporting line',
          kind: 'TEXT',
          required: false,
          maxLength: 160,
          defaultValue: '{{brand.tagline}}',
          help: null,
        },
        {
          key: 'cta',
          label: 'Call to action',
          kind: 'TEXT',
          required: false,
          maxLength: 30,
          defaultValue: 'Learn more',
          help: null,
        },
      ],
      pages: [
        {
          id: 'page1',
          background: { fill: brand('secondary'), imageSlot: 'photo' },
          layers: [
            {
              type: 'rect',
              id: 'band',
              box: { x: 0, y: 0.56, w: 1, h: 0.44 },
              fill: hex('#000000'),
              opacity: 0.55,
              radius: 0,
            },
            {
              type: 'text',
              id: 'headlineText',
              box: { x: 0.07, y: 0.6, w: 0.86, h: 0.18 },
              field: 'headline',
              font: 'heading',
              sizeRatio: 0.055,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            {
              type: 'text',
              id: 'sublineText',
              box: { x: 0.07, y: 0.79, w: 0.86, h: 0.08 },
              field: 'subline',
              font: 'body',
              sizeRatio: 0.028,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'normal',
              autofit: false,
            },
            {
              type: 'rect',
              id: 'ctaPill',
              box: { x: 0.07, y: 0.885, w: 0.34, h: 0.07 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0.5,
            },
            {
              type: 'text',
              id: 'ctaText',
              box: { x: 0.07, y: 0.9, w: 0.34, h: 0.045 },
              field: 'cta',
              font: 'body',
              sizeRatio: 0.026,
              color: hex('#FFFFFF'),
              align: 'center',
              weight: 'bold',
              autofit: true,
            },
            { type: 'logo', id: 'logo', box: { x: 0.78, y: 0.04, w: 0.18, h: 0.1 } },
          ],
        },
      ],
    },
  },
  {
    key: 'tips-carousel',
    version: 1,
    name: 'Tips carousel',
    description: 'Three slides: a cover, a tip, and a closing call to action.',
    category: 'CAROUSEL',
    formats: ['INSTAGRAM_SQUARE', 'INSTAGRAM_PORTRAIT', 'LINKEDIN_POST'],
    defaultFormat: 'INSTAGRAM_PORTRAIT',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'coverTitle',
          label: 'Cover title',
          kind: 'TEXT',
          required: true,
          maxLength: 80,
          defaultValue: null,
          help: null,
        },
        {
          key: 'tipTitle',
          label: 'Tip title',
          kind: 'TEXT',
          required: true,
          maxLength: 80,
          defaultValue: null,
          help: null,
        },
        {
          key: 'tipBody',
          label: 'Tip detail',
          kind: 'TEXT',
          required: false,
          maxLength: 400,
          defaultValue: null,
          help: null,
        },
        {
          key: 'closing',
          label: 'Closing line',
          kind: 'TEXT',
          required: false,
          maxLength: 120,
          defaultValue: 'Follow {{brand.name}} for more',
          help: null,
        },
      ],
      pages: [
        {
          id: 'cover',
          background: { fill: brand('primary'), imageSlot: null },
          layers: [
            {
              type: 'text',
              id: 'coverTitleText',
              box: { x: 0.08, y: 0.3, w: 0.84, h: 0.34 },
              field: 'coverTitle',
              font: 'heading',
              sizeRatio: 0.07,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            {
              type: 'rect',
              id: 'coverRule',
              box: { x: 0.08, y: 0.68, w: 0.2, h: 0.01 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0.5,
            },
            { type: 'logo', id: 'coverLogo', box: { x: 0.08, y: 0.84, w: 0.2, h: 0.1 } },
          ],
        },
        {
          id: 'tip',
          background: { fill: brand('background'), imageSlot: null },
          layers: [
            {
              type: 'rect',
              id: 'tipMarker',
              box: { x: 0.08, y: 0.12, w: 0.1, h: 0.012 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0.5,
            },
            {
              type: 'text',
              id: 'tipTitleText',
              box: { x: 0.08, y: 0.16, w: 0.84, h: 0.2 },
              field: 'tipTitle',
              font: 'heading',
              sizeRatio: 0.05,
              color: brand('text'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            {
              type: 'text',
              id: 'tipBodyText',
              box: { x: 0.08, y: 0.4, w: 0.84, h: 0.48 },
              field: 'tipBody',
              font: 'body',
              sizeRatio: 0.03,
              color: brand('text'),
              align: 'left',
              weight: 'normal',
              autofit: true,
            },
          ],
        },
        {
          id: 'closing',
          background: { fill: brand('secondary'), imageSlot: null },
          layers: [
            {
              type: 'text',
              id: 'closingText',
              box: { x: 0.1, y: 0.36, w: 0.8, h: 0.2 },
              field: 'closing',
              font: 'heading',
              sizeRatio: 0.05,
              color: hex('#FFFFFF'),
              align: 'center',
              weight: 'bold',
              autofit: true,
            },
            { type: 'logo', id: 'closingLogo', box: { x: 0.35, y: 0.62, w: 0.3, h: 0.14 } },
          ],
        },
      ],
    },
  },
  {
    key: 'youtube-thumbnail',
    version: 1,
    name: 'YouTube thumbnail',
    description:
      'A still on the left, a bold title on the right, and an accent edge. Exported within YouTube’s 2 MB limit.',
    category: 'THUMBNAIL',
    formats: ['YOUTUBE_THUMBNAIL'],
    defaultFormat: 'YOUTUBE_THUMBNAIL',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'still',
          label: 'Video still',
          kind: 'IMAGE',
          required: false,
          maxLength: 280,
          defaultValue: null,
          help: null,
        },
        {
          key: 'title',
          label: 'Title',
          kind: 'TEXT',
          required: true,
          maxLength: 60,
          defaultValue: null,
          help: 'Short titles read best at thumbnail size.',
        },
      ],
      pages: [
        {
          id: 'page1',
          background: { fill: brand('primary'), imageSlot: null },
          layers: [
            {
              type: 'image',
              id: 'stillImage',
              box: { x: 0, y: 0, w: 0.52, h: 1 },
              slot: 'still',
              fit: 'cover',
            },
            {
              type: 'rect',
              id: 'edge',
              box: { x: 0.52, y: 0, w: 0.015, h: 1 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0,
            },
            {
              type: 'text',
              id: 'titleText',
              box: { x: 0.57, y: 0.12, w: 0.39, h: 0.62 },
              field: 'title',
              font: 'heading',
              sizeRatio: 0.1,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            { type: 'logo', id: 'logo', box: { x: 0.57, y: 0.8, w: 0.16, h: 0.13 } },
          ],
        },
      ],
    },
  },
  {
    key: 'event-flyer',
    version: 1,
    name: 'Event flyer',
    description:
      'A printable flyer: title, date and venue, details, a photo and the brand’s website.',
    category: 'FLYER',
    formats: ['FLYER_A4', 'FLYER_LETTER', 'INSTAGRAM_PORTRAIT'],
    defaultFormat: 'FLYER_A4',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'title',
          label: 'Event title',
          kind: 'TEXT',
          required: true,
          maxLength: 80,
          defaultValue: null,
          help: null,
        },
        {
          key: 'when',
          label: 'Date and time',
          kind: 'TEXT',
          required: true,
          maxLength: 80,
          defaultValue: null,
          help: null,
        },
        {
          key: 'where',
          label: 'Venue',
          kind: 'TEXT',
          required: false,
          maxLength: 120,
          defaultValue: null,
          help: null,
        },
        {
          key: 'details',
          label: 'Details',
          kind: 'TEXT',
          required: false,
          maxLength: 600,
          defaultValue: null,
          help: null,
        },
        {
          key: 'photo',
          label: 'Photo',
          kind: 'IMAGE',
          required: false,
          maxLength: 280,
          defaultValue: null,
          help: null,
        },
        {
          key: 'footer',
          label: 'Footer',
          kind: 'TEXT',
          required: false,
          maxLength: 120,
          defaultValue: '{{brand.website}}',
          help: null,
        },
      ],
      pages: [
        {
          id: 'page1',
          background: { fill: brand('background'), imageSlot: null },
          layers: [
            {
              type: 'rect',
              id: 'header',
              box: { x: 0, y: 0, w: 1, h: 0.3 },
              fill: brand('primary'),
              opacity: 1,
              radius: 0,
            },
            {
              type: 'text',
              id: 'titleText',
              box: { x: 0.07, y: 0.06, w: 0.66, h: 0.2 },
              field: 'title',
              font: 'heading',
              sizeRatio: 0.05,
              color: hex('#FFFFFF'),
              align: 'left',
              weight: 'bold',
              autofit: true,
            },
            { type: 'logo', id: 'logo', box: { x: 0.76, y: 0.08, w: 0.18, h: 0.12 } },
            {
              type: 'text',
              id: 'whenText',
              box: { x: 0.07, y: 0.33, w: 0.86, h: 0.05 },
              field: 'when',
              font: 'heading',
              sizeRatio: 0.028,
              color: brand('accent'),
              align: 'left',
              weight: 'bold',
              autofit: false,
            },
            {
              type: 'text',
              id: 'whereText',
              box: { x: 0.07, y: 0.385, w: 0.86, h: 0.045 },
              field: 'where',
              font: 'body',
              sizeRatio: 0.022,
              color: brand('text'),
              align: 'left',
              weight: 'normal',
              autofit: false,
            },
            {
              type: 'image',
              id: 'photoImage',
              box: { x: 0.07, y: 0.45, w: 0.86, h: 0.26 },
              slot: 'photo',
              fit: 'cover',
            },
            {
              type: 'text',
              id: 'detailsText',
              box: { x: 0.07, y: 0.73, w: 0.86, h: 0.18 },
              field: 'details',
              font: 'body',
              sizeRatio: 0.019,
              color: brand('text'),
              align: 'left',
              weight: 'normal',
              autofit: true,
            },
            {
              type: 'rect',
              id: 'footerBar',
              box: { x: 0, y: 0.94, w: 1, h: 0.06 },
              fill: brand('secondary'),
              opacity: 1,
              radius: 0,
            },
            {
              type: 'text',
              id: 'footerText',
              box: { x: 0.07, y: 0.952, w: 0.86, h: 0.036 },
              field: 'footer',
              font: 'body',
              sizeRatio: 0.018,
              color: hex('#FFFFFF'),
              align: 'center',
              weight: 'normal',
              autofit: true,
            },
          ],
        },
      ],
    },
  },
  {
    key: 'product-spotlight',
    version: 1,
    name: 'Product spotlight',
    description:
      'A product image with its name and description from the brand kit, and a call to action.',
    category: 'POSTER',
    formats: ['POSTER_A3', 'INSTAGRAM_PORTRAIT', 'PINTEREST_PIN', 'STORY_VERTICAL'],
    defaultFormat: 'PINTEREST_PIN',
    layout: {
      schemaVersion: 1,
      fields: [
        {
          key: 'productImage',
          label: 'Product image',
          kind: 'IMAGE',
          required: true,
          maxLength: 280,
          defaultValue: null,
          help: null,
        },
        {
          key: 'productName',
          label: 'Product name',
          kind: 'TEXT',
          required: true,
          maxLength: 80,
          defaultValue: '{{product.name}}',
          help: null,
        },
        {
          key: 'productDescription',
          label: 'Description',
          kind: 'TEXT',
          required: false,
          maxLength: 300,
          defaultValue: '{{product.description}}',
          help: null,
        },
        {
          key: 'cta',
          label: 'Call to action',
          kind: 'TEXT',
          required: false,
          maxLength: 40,
          defaultValue: 'Shop now',
          help: null,
        },
      ],
      pages: [
        {
          id: 'page1',
          background: { fill: brand('background'), imageSlot: null },
          layers: [
            {
              type: 'image',
              id: 'product',
              box: { x: 0.08, y: 0.06, w: 0.84, h: 0.5 },
              slot: 'productImage',
              fit: 'contain',
            },
            {
              type: 'text',
              id: 'nameText',
              box: { x: 0.08, y: 0.6, w: 0.84, h: 0.12 },
              field: 'productName',
              font: 'heading',
              sizeRatio: 0.045,
              color: brand('text'),
              align: 'center',
              weight: 'bold',
              autofit: true,
            },
            {
              type: 'text',
              id: 'descriptionText',
              box: { x: 0.1, y: 0.73, w: 0.8, h: 0.12 },
              field: 'productDescription',
              font: 'body',
              sizeRatio: 0.022,
              color: brand('text'),
              align: 'center',
              weight: 'normal',
              autofit: true,
            },
            {
              type: 'rect',
              id: 'ctaPill',
              box: { x: 0.3, y: 0.87, w: 0.4, h: 0.06 },
              fill: brand('accent'),
              opacity: 1,
              radius: 0.5,
            },
            {
              type: 'text',
              id: 'ctaText',
              box: { x: 0.3, y: 0.882, w: 0.4, h: 0.036 },
              field: 'cta',
              font: 'body',
              sizeRatio: 0.022,
              color: hex('#FFFFFF'),
              align: 'center',
              weight: 'bold',
              autofit: true,
            },
            { type: 'logo', id: 'logo', box: { x: 0.84, y: 0.94, w: 0.12, h: 0.05 } },
          ],
        },
      ],
    },
  },
];

export function getBuiltInTemplate(key: string): BuiltInTemplate | undefined {
  return BUILT_IN_TEMPLATES.find((template) => template.key === key);
}
