import { randomUUID } from 'node:crypto';

import { Injectable, UnprocessableEntityException } from '@nestjs/common';
import {
  DESIGN_FORMATS,
  brandKitSchema,
  getDesignFormat,
  type CreateDesignInput,
  type CreateDesignTemplateInput,
  type DesignReviewInput,
  type ExportDesignInput,
  type TemplateLayout,
  type UpdateDesignInput,
  type UpdateDesignTemplateInput,
} from '@spectra/contracts';
import { Prisma } from '@spectra/database';
import {
  BUILT_IN_TEMPLATES,
  DesignValidationError,
  buildImagePdf,
  buildRenderPlan,
  getBuiltInTemplate,
  renderPlanHash,
  validateTemplateLayout,
  type BrandContext,
  type RenderPlan,
} from '@spectra/design-studio';
import { DesignRenderError, SharpDesignRenderer } from '@spectra/media-sharp';
import { reconcile, release, reserve } from '@spectra/metering';
import { TenantIsolationError } from '@spectra/security';
import {
  S3ObjectStorageProvider,
  assertKeyWithinTenant,
  buildObjectKey,
  validateUpload,
} from '@spectra/storage';

import { getApiEnv } from '../config/env';
import { AuditService } from '../infra/audit.service';
import { UsageService } from '../infra/usage.service';
import { PrismaService } from '../prisma/prisma.service';
import type { Principal, TenantContext } from '../auth/types';

/** Raster inputs the renderer decodes. SVG is refused: it is markup, not pixels. */
const IMAGE_MIME_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp']);
const FONT_MIME_TYPES = new Set(['font/ttf', 'font/otf']);
const MAX_IMAGE_BYTES = 25 * 1024 * 1024;
const MAX_FONT_BYTES = 5 * 1024 * 1024;
const PREVIEW_MAX_WIDTH = 720;
const SIGNED_URL_TTL_SECONDS = 15 * 60;

type Scope = { organizationId: string; workspaceId: string };

const RENDER_SELECT = {
  id: true,
  outputFormat: true,
  pageIndex: true,
  pageCount: true,
  formatKey: true,
  widthPx: true,
  heightPx: true,
  engine: true,
  engineVersion: true,
  durationMs: true,
  warnings: true,
  createdAt: true,
  renderHash: true,
  mediaAsset: { select: { id: true, mimeType: true, sizeBytes: true, storageKey: false } },
} as const;

/**
 * Design studio (Phase 7A, ADR-0040): templates, designs, real previews and
 * exports, and the design approval workflow.
 *
 * Every image a user sees here was rendered by sharp from the design's own
 * render plan. Exports are stored under the tenant's renders/ prefix as media
 * assets, so the calendar, publishing and the media library use them like any
 * other file. Foreign or missing ids — designs, templates, brands, images,
 * fonts — are the same 404.
 */
@Injectable()
export class StudioService {
  private readonly storage: S3ObjectStorageProvider;
  private readonly renderer = new SharpDesignRenderer();
  private bucketReady = false;

  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly usage: UsageService,
  ) {
    this.storage = new S3ObjectStorageProvider(getApiEnv());
  }

  private scope(tenant: TenantContext): Scope {
    return { organizationId: tenant.organizationId, workspaceId: tenant.workspaceId as string };
  }

  private invalid(error: unknown): never {
    if (error instanceof DesignValidationError)
      throw new UnprocessableEntityException(error.message);
    throw error;
  }

  // -------------------------------------------------------------------------
  // Capabilities, formats, templates
  // -------------------------------------------------------------------------

  capabilities() {
    return {
      engine: this.renderer.id,
      engineVersion: this.renderer.engineVersion,
      outputs: ['PNG', 'JPEG', 'PDF'],
      pdf: 'Raster PDF: each page is the rendered JPEG embedded at the format’s dpi — not editable vector text.',
      fonts:
        'Brand fonts render from an uploaded TTF/OTF file. A font named without a file renders only if the API host has it installed; otherwise the host’s fallback font is used, and the export says so.',
      aiImageGeneration: false,
      note: 'Designs are rendered locally from templates, brand kits and your own images. Nothing is generated by an AI image model.',
    };
  }

  formats() {
    return DESIGN_FORMATS;
  }

  async listTemplates(tenant: TenantContext) {
    const workspace = await this.prisma.client.designTemplate.findMany({
      where: { ...this.scope(tenant), deletedAt: null, status: 'ACTIVE' },
      orderBy: { updatedAt: 'desc' },
    });
    return {
      builtIn: BUILT_IN_TEMPLATES.map((template) => ({ ...template, source: 'BUILT_IN' as const })),
      workspace: workspace.map((template) => ({ ...template, source: 'WORKSPACE' as const })),
    };
  }

  async getTemplate(tenant: TenantContext, id: string) {
    const template = await this.prisma.client.designTemplate.findFirst({
      where: { id, ...this.scope(tenant), deletedAt: null },
    });
    if (!template) throw new TenantIsolationError();
    return template;
  }

  async createTemplate(
    tenant: TenantContext,
    principal: Principal,
    input: CreateDesignTemplateInput,
  ) {
    let layout: TemplateLayout;
    if (input.fromBuiltInKey) {
      const builtIn = getBuiltInTemplate(input.fromBuiltInKey);
      if (!builtIn) throw new TenantIsolationError();
      layout = builtIn.layout;
    } else {
      try {
        layout = validateTemplateLayout(input.layout);
      } catch (error) {
        this.invalid(error);
      }
    }
    const template = await this.prisma.client.designTemplate.create({
      data: {
        ...this.scope(tenant),
        name: input.name,
        description: input.description ?? null,
        category: input.category,
        layout: layout as unknown as Prisma.InputJsonValue,
        formats: input.formats,
        defaultFormat: input.defaultFormat,
        sourceBuiltInKey: input.fromBuiltInKey ?? null,
        createdById: principal.userId,
        updatedById: principal.userId,
      },
    });
    await this.audit.record({
      ...this.scope(tenant),
      actorUserId: principal.userId,
      action: 'design_template.created',
      resourceType: 'DesignTemplate',
      resourceId: template.id,
      changes: {
        name: input.name,
        category: input.category,
        fromBuiltInKey: input.fromBuiltInKey ?? null,
      },
    });
    return template;
  }

  async updateTemplate(
    tenant: TenantContext,
    principal: Principal,
    id: string,
    input: UpdateDesignTemplateInput,
  ) {
    const existing = await this.getTemplate(tenant, id);
    let layout: TemplateLayout | undefined;
    if (input.layout) {
      try {
        layout = validateTemplateLayout(input.layout);
      } catch (error) {
        this.invalid(error);
      }
    }
    const formats = input.formats ?? existing.formats;
    const defaultFormat = input.defaultFormat ?? existing.defaultFormat;
    if (!formats.includes(defaultFormat)) {
      throw new UnprocessableEntityException('defaultFormat must be one of formats.');
    }
    const template = await this.prisma.client.designTemplate.update({
      where: { id: existing.id },
      data: {
        ...(input.name !== undefined ? { name: input.name } : {}),
        ...(input.description !== undefined ? { description: input.description } : {}),
        ...(input.category !== undefined ? { category: input.category } : {}),
        formats,
        defaultFormat,
        ...(layout
          ? { layout: layout as unknown as Prisma.InputJsonValue, version: { increment: 1 } }
          : {}),
        updatedById: principal.userId,
      },
    });
    await this.audit.record({
      ...this.scope(tenant),
      actorUserId: principal.userId,
      action: 'design_template.updated',
      resourceType: 'DesignTemplate',
      resourceId: id,
      changes: { layoutChanged: Boolean(layout), version: template.version },
    });
    return template;
  }

  async archiveTemplate(tenant: TenantContext, principal: Principal, id: string) {
    await this.getTemplate(tenant, id);
    const template = await this.prisma.client.designTemplate.update({
      where: { id },
      data: { status: 'ARCHIVED', deletedAt: new Date() },
    });
    await this.audit.record({
      ...this.scope(tenant),
      actorUserId: principal.userId,
      action: 'design_template.archived',
      resourceType: 'DesignTemplate',
      resourceId: id,
    });
    return template;
  }

  // -------------------------------------------------------------------------
  // Designs
  // -------------------------------------------------------------------------

  listDesigns(tenant: TenantContext, filter: { contentItemId?: string; campaignId?: string } = {}) {
    return this.prisma.client.design.findMany({
      where: {
        ...this.scope(tenant),
        deletedAt: null,
        ...(filter.contentItemId ? { contentItemId: filter.contentItemId } : {}),
        ...(filter.campaignId ? { campaignId: filter.campaignId } : {}),
      },
      orderBy: { updatedAt: 'desc' },
      take: 200,
      include: {
        brand: { select: { id: true, name: true } },
        renders: { select: RENDER_SELECT, orderBy: { createdAt: 'desc' }, take: 12 },
      },
    });
  }

  async getDesign(tenant: TenantContext, id: string) {
    const design = await this.prisma.client.design.findFirst({
      where: { id, ...this.scope(tenant), deletedAt: null },
      include: {
        brand: { select: { id: true, name: true } },
        contentItem: { select: { id: true, title: true, lifecycleState: true } },
        campaign: { select: { id: true, name: true } },
        renders: { select: RENDER_SELECT, orderBy: { createdAt: 'desc' }, take: 50 },
      },
    });
    if (!design) throw new TenantIsolationError();
    return design;
  }

  async createDesign(tenant: TenantContext, principal: Principal, input: CreateDesignInput) {
    const scope = this.scope(tenant);
    let layout: TemplateLayout;
    let templateId: string | null = null;
    let builtInKey: string | null = null;
    let version: number;
    let category: CreateDesignTemplateInput['category'];
    let formats: string[];
    if ('builtInKey' in input.template) {
      const builtIn = getBuiltInTemplate(input.template.builtInKey);
      if (!builtIn) throw new TenantIsolationError();
      ({ layout, version, category, formats } = builtIn);
      builtInKey = builtIn.key;
    } else {
      const template = await this.getTemplate(tenant, input.template.templateId);
      layout = validateTemplateLayout(template.layout);
      ({ version, category, formats } = template);
      templateId = template.id;
    }
    if (!formats.includes(input.formatKey)) {
      throw new UnprocessableEntityException(
        `This template is made for ${formats.join(', ')}; ${input.formatKey} is not one of them.`,
      );
    }
    await this.assertLinks(scope, input);
    const brand = await this.brandContext(scope, input.brandId ?? null);
    await this.verifyPlan(scope, layout, input.formatKey, brand, input.values, input.images, false);

    const design = await this.prisma.client.design.create({
      data: {
        ...scope,
        name: input.name,
        templateId,
        templateBuiltInKey: builtInKey,
        templateVersion: version,
        category,
        layout: layout as unknown as Prisma.InputJsonValue,
        brandId: input.brandId ?? null,
        formatKey: input.formatKey,
        values: input.values as Prisma.InputJsonValue,
        images: input.images as Prisma.InputJsonValue,
        contentItemId: input.contentItemId ?? null,
        campaignId: input.campaignId ?? null,
        createdById: principal.userId,
      },
    });
    await this.audit.record({
      ...scope,
      actorUserId: principal.userId,
      action: 'design.created',
      resourceType: 'Design',
      resourceId: design.id,
      changes: { template: builtInKey ?? templateId, formatKey: input.formatKey },
    });
    return this.getDesign(tenant, design.id);
  }

  async updateDesign(
    tenant: TenantContext,
    principal: Principal,
    id: string,
    input: UpdateDesignInput,
  ) {
    const scope = this.scope(tenant);
    const existing = await this.getDesign(tenant, id);
    if (existing.status === 'ARCHIVED')
      throw new UnprocessableEntityException('This design is archived.');
    const layout = existing.layout as unknown as TemplateLayout;
    const next = {
      brandId: input.brandId !== undefined ? input.brandId : existing.brandId,
      formatKey: input.formatKey ?? existing.formatKey,
      values: input.values ?? (existing.values as Record<string, string>),
      images: input.images ?? (existing.images as Record<string, string>),
    };
    await this.assertLinks(scope, input);
    const brand = await this.brandContext(scope, next.brandId ?? null);
    await this.verifyPlan(scope, layout, next.formatKey, brand, next.values, next.images, false);

    const changesVisuals =
      input.brandId !== undefined ||
      input.formatKey !== undefined ||
      input.values !== undefined ||
      input.images !== undefined;
    const wasApproved = existing.status === 'APPROVED' || existing.status === 'IN_REVIEW';
    await this.prisma.client.design.update({
      where: { id: existing.id },
      data: {
        ...(input.name !== undefined ? { name: input.name } : {}),
        brandId: next.brandId ?? null,
        formatKey: next.formatKey,
        values: next.values as Prisma.InputJsonValue,
        images: next.images as Prisma.InputJsonValue,
        ...(input.contentItemId !== undefined ? { contentItemId: input.contentItemId } : {}),
        ...(input.campaignId !== undefined ? { campaignId: input.campaignId } : {}),
        // An approval covers what was approved. Changing the visuals sends the
        // design back to draft; attaching it to content or a campaign does not.
        ...(changesVisuals && wasApproved
          ? {
              status: 'DRAFT' as const,
              approvedAt: null,
              approvedById: null,
              submittedAt: null,
              reviewNote: 'Edited after review — needs approval again.',
            }
          : {}),
      },
    });
    await this.audit.record({
      ...scope,
      actorUserId: principal.userId,
      action: 'design.updated',
      resourceType: 'Design',
      resourceId: id,
      changes: { visuals: changesVisuals, resetApproval: changesVisuals && wasApproved },
    });
    return this.getDesign(tenant, id);
  }

  async archiveDesign(tenant: TenantContext, principal: Principal, id: string) {
    await this.getDesign(tenant, id);
    await this.prisma.client.design.update({
      where: { id },
      data: { status: 'ARCHIVED', deletedAt: new Date() },
    });
    await this.audit.record({
      ...this.scope(tenant),
      actorUserId: principal.userId,
      action: 'design.archived',
      resourceType: 'Design',
      resourceId: id,
    });
    return { id, archived: true };
  }

  // -------------------------------------------------------------------------
  // Rendering
  // -------------------------------------------------------------------------

  /** A real render of one page, scaled down for the editor. Not stored. */
  async preview(tenant: TenantContext, id: string, pageIndex: number) {
    const design = await this.getDesign(tenant, id);
    const scope = this.scope(tenant);
    const { plan, loader } = await this.planFor(scope, design);
    if (pageIndex < 0 || pageIndex >= plan.pages.length) {
      throw new UnprocessableEntityException(`This design has ${plan.pages.length} page(s).`);
    }
    const page = await this.renderPage(
      plan,
      pageIndex,
      { format: 'png', quality: 90, maxWidth: PREVIEW_MAX_WIDTH },
      loader,
    );
    return {
      buffer: page.buffer,
      warnings: [...plan.warnings, ...page.warnings],
      pageCount: plan.pages.length,
    };
  }

  async exportDesign(
    tenant: TenantContext,
    principal: Principal,
    id: string,
    input: ExportDesignInput,
  ) {
    const scope = this.scope(tenant);
    const design = await this.getDesign(tenant, id);
    if (design.status === 'ARCHIVED')
      throw new UnprocessableEntityException('This design is archived.');
    const { plan, loader, versions } = await this.planFor(scope, design);
    const hash = renderPlanHash(
      plan,
      { format: input.outputFormat, quality: input.quality },
      versions,
    );
    const keys =
      input.outputFormat === 'PDF'
        ? [`${hash}:pdf`]
        : plan.pages.map((page) => `${hash}:p${page.index}`);

    const existing = await this.prisma.client.designRender.findMany({
      where: { ...scope, designId: design.id, renderKey: { in: keys } },
      select: RENDER_SELECT,
      orderBy: { pageIndex: 'asc' },
    });
    if (existing.length === keys.length) {
      return { reused: true, warnings: plan.warnings, renders: existing };
    }

    // Local rendering bills nobody, but it is real work: it counts against a
    // per-operation MEDIA_RENDER limit, checked before anything is drawn.
    const reservationKey = `design-export-${design.id}-${hash}`;
    await reserve(this.prisma.client, {
      ...scope,
      kind: 'MEDIA_RENDER',
      provider: 'sharp',
      requests: plan.pages.length,
      idempotencyKey: reservationKey,
      resourceType: 'DESIGN',
      resourceId: design.id,
      ttlMs: 5 * 60_000,
    });

    await this.ensureBucket();
    const warnings = [...plan.warnings];
    const stored: string[] = [];
    try {
      const outputs: Array<{
        key: string;
        pageIndex: number | null;
        buffer: Buffer;
        mimeType: string;
        width: number;
        height: number;
        durationMs: number;
        warnings: string[];
      }> = [];
      if (input.outputFormat === 'PDF') {
        const pages = [];
        let duration = 0;
        const pageWarnings: string[] = [];
        for (const page of plan.pages) {
          const rendered = await this.renderPage(
            plan,
            page.index,
            { format: 'jpeg', quality: input.quality },
            loader,
          );
          duration += rendered.durationMs;
          pageWarnings.push(...rendered.warnings);
          pages.push({ jpeg: rendered.buffer, widthPx: rendered.width, heightPx: rendered.height });
        }
        const pdf = buildImagePdf(pages, plan.format.dpi);
        outputs.push({
          key: `${hash}:pdf`,
          pageIndex: null,
          buffer: pdf,
          mimeType: 'application/pdf',
          width: plan.format.width,
          height: plan.format.height,
          durationMs: duration,
          warnings: pageWarnings,
        });
      } else {
        for (const page of plan.pages) {
          const rendered = await this.renderPage(
            plan,
            page.index,
            { format: input.outputFormat === 'PNG' ? 'png' : 'jpeg', quality: input.quality },
            loader,
          );
          outputs.push({
            key: `${hash}:p${page.index}`,
            pageIndex: page.index,
            buffer: rendered.buffer,
            mimeType: rendered.mimeType,
            width: rendered.width,
            height: rendered.height,
            durationMs: rendered.durationMs,
            warnings: rendered.warnings,
          });
        }
      }

      const renders = [];
      for (const output of outputs) {
        const check = validateUpload({
          domain: 'renders',
          mimeType: output.mimeType,
          sizeBytes: output.buffer.length,
        });
        if (!check.ok)
          throw new UnprocessableEntityException(
            `The export could not be stored: ${check.message}`,
          );
        const assetId = randomUUID();
        const extension =
          output.mimeType === 'application/pdf'
            ? 'pdf'
            : output.mimeType === 'image/png'
              ? 'png'
              : 'jpg';
        const storageKey = buildObjectKey({
          ...scope,
          domain: 'renders',
          resourceId: assetId,
          filename: `design-${design.id.slice(0, 8)}${output.pageIndex === null ? '' : `-p${output.pageIndex + 1}`}.${extension}`,
        });
        await this.storage.putObject({
          key: storageKey,
          body: output.buffer,
          contentType: output.mimeType,
        });
        stored.push(storageKey);
        warnings.push(...output.warnings);
        try {
          const render = await this.prisma.client.$transaction(async (tx) => {
            await tx.mediaAsset.create({
              data: {
                id: assetId,
                ...scope,
                kind: output.mimeType === 'application/pdf' ? 'DOCUMENT' : 'IMAGE',
                storageKey,
                mimeType: output.mimeType,
                sizeBytes: output.buffer.length,
                widthPx: output.width,
                heightPx: output.height,
                engine: this.renderer.id,
                createdById: principal.userId,
              },
            });
            return tx.designRender.create({
              data: {
                ...scope,
                designId: design.id,
                mediaAssetId: assetId,
                outputFormat: input.outputFormat,
                pageIndex: output.pageIndex,
                pageCount: plan.pages.length,
                formatKey: plan.format.key,
                widthPx: output.width,
                heightPx: output.height,
                renderHash: hash,
                renderKey: output.key,
                engine: this.renderer.id,
                engineVersion: this.renderer.engineVersion,
                durationMs: output.durationMs,
                warnings: [...new Set([...plan.warnings, ...output.warnings])],
                createdById: principal.userId,
              },
              select: RENDER_SELECT,
            });
          });
          renders.push(render);
        } catch (error) {
          // A concurrent export of the same inputs got there first: keep its
          // row, drop this copy of the bytes.
          if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
            await this.storage.deleteObject(storageKey).catch(() => undefined);
            const winner = await this.prisma.client.designRender.findFirst({
              where: { ...scope, renderKey: output.key },
              select: RENDER_SELECT,
            });
            if (winner) renders.push(winner);
            continue;
          }
          throw error;
        }
      }

      await this.usage.record(scope, {
        kind: 'MEDIA_RENDER',
        provider: 'sharp',
        requests: plan.pages.length,
        bytes: outputs.reduce((sum, output) => sum + output.buffer.length, 0),
        resourceType: 'DESIGN',
        resourceId: design.id,
        metadata: {
          outputFormat: input.outputFormat,
          formatKey: plan.format.key,
          pages: plan.pages.length,
        },
      });
      await reconcile(this.prisma.client, scope, reservationKey);
      await this.audit.record({
        ...scope,
        actorUserId: principal.userId,
        action: 'design.exported',
        resourceType: 'Design',
        resourceId: design.id,
        changes: {
          outputFormat: input.outputFormat,
          pages: plan.pages.length,
          formatKey: plan.format.key,
        },
      });
      return { reused: false, warnings: [...new Set(warnings)], renders };
    } catch (error) {
      await release(this.prisma.client, scope, reservationKey);
      throw error;
    }
  }

  async renderUrl(tenant: TenantContext, renderId: string) {
    const render = await this.prisma.client.designRender.findFirst({
      where: { id: renderId, ...this.scope(tenant) },
      select: { id: true, mediaAsset: { select: { storageKey: true, mimeType: true } } },
    });
    if (!render) throw new TenantIsolationError();
    assertKeyWithinTenant(render.mediaAsset.storageKey, this.scope(tenant));
    const signed = await this.storage.createSignedDownloadUrl(
      render.mediaAsset.storageKey,
      SIGNED_URL_TTL_SECONDS,
    );
    return {
      renderId: render.id,
      url: signed.url,
      expiresAt: signed.expiresAt.toISOString(),
      mimeType: render.mediaAsset.mimeType,
    };
  }

  // -------------------------------------------------------------------------
  // Workflow
  // -------------------------------------------------------------------------

  async submit(tenant: TenantContext, principal: Principal, id: string) {
    const design = await this.getDesign(tenant, id);
    if (design.status !== 'DRAFT') {
      throw new UnprocessableEntityException(
        `A design can be submitted for review from DRAFT, not ${design.status}.`,
      );
    }
    if (design.renders.length === 0) {
      throw new UnprocessableEntityException(
        'Export the design at least once before submitting it — reviewers approve rendered files.',
      );
    }
    return this.transition(
      tenant,
      principal,
      id,
      'IN_REVIEW',
      { submittedAt: new Date(), reviewNote: null },
      'design.submitted',
    );
  }

  async approve(tenant: TenantContext, principal: Principal, id: string, input: DesignReviewInput) {
    const design = await this.getDesign(tenant, id);
    if (design.status !== 'IN_REVIEW') {
      throw new UnprocessableEntityException(
        `Only a design in review can be approved (this one is ${design.status}).`,
      );
    }
    return this.transition(
      tenant,
      principal,
      id,
      'APPROVED',
      { approvedAt: new Date(), approvedById: principal.userId, reviewNote: input.note ?? null },
      'design.approved',
    );
  }

  async requestChanges(
    tenant: TenantContext,
    principal: Principal,
    id: string,
    input: DesignReviewInput,
  ) {
    const design = await this.getDesign(tenant, id);
    if (design.status !== 'IN_REVIEW' && design.status !== 'APPROVED') {
      throw new UnprocessableEntityException(
        `Changes can be requested on a design in review or approved, not ${design.status}.`,
      );
    }
    return this.transition(
      tenant,
      principal,
      id,
      'DRAFT',
      { approvedAt: null, approvedById: null, reviewNote: input.note ?? 'Changes requested.' },
      'design.changes_requested',
    );
  }

  private async transition(
    tenant: TenantContext,
    principal: Principal,
    id: string,
    status: 'DRAFT' | 'IN_REVIEW' | 'APPROVED',
    data: Prisma.DesignUncheckedUpdateManyInput,
    action: string,
  ) {
    const scope = this.scope(tenant);
    await this.prisma.client.design.updateMany({
      where: { id, ...scope },
      data: { ...data, status },
    });
    await this.audit.record({
      ...scope,
      actorUserId: principal.userId,
      action,
      resourceType: 'Design',
      resourceId: id,
      changes: { status },
    });
    return this.getDesign(tenant, id);
  }

  // -------------------------------------------------------------------------
  // Internals
  // -------------------------------------------------------------------------

  private async ensureBucket() {
    if (!this.bucketReady) {
      await this.storage.ensureBucket();
      this.bucketReady = true;
    }
  }

  private async assertLinks(
    scope: Scope,
    input: { contentItemId?: string | null; campaignId?: string | null; brandId?: string | null },
  ) {
    if (input.contentItemId) {
      const item = await this.prisma.client.contentItem.findFirst({
        where: { id: input.contentItemId, ...scope, deletedAt: null },
        select: { id: true },
      });
      if (!item) throw new TenantIsolationError();
    }
    if (input.campaignId) {
      const campaign = await this.prisma.client.campaign.findFirst({
        where: { id: input.campaignId, ...scope, deletedAt: null },
        select: { id: true },
      });
      if (!campaign) throw new TenantIsolationError();
    }
  }

  /** The brand as the plan needs it: name, website and a validated brand kit. */
  async brandContext(scope: Scope, brandId: string | null): Promise<BrandContext | null> {
    if (!brandId) return null;
    const brand = await this.prisma.client.brand.findFirst({
      where: { id: brandId, ...scope, deletedAt: null },
    });
    if (!brand) throw new TenantIsolationError();
    const kit = brandKitSchema.safeParse({
      logoAssetId: brand.logoAssetId,
      palette: brand.palette ?? {},
      typography: brand.typography ?? {},
      tagline: brand.tagline,
      visualStyle: brand.visualStyle,
      offerings: brand.offerings ?? [],
    });
    return { name: brand.name, websiteUrl: brand.websiteUrl, kit: kit.success ? kit.data : null };
  }

  private async planFor(
    scope: Scope,
    design: {
      layout: unknown;
      formatKey: string;
      brandId: string | null;
      values: unknown;
      images: unknown;
    },
  ) {
    const brand = await this.brandContext(scope, design.brandId);
    return this.verifyPlan(
      scope,
      design.layout as TemplateLayout,
      design.formatKey,
      brand,
      design.values as Record<string, string>,
      design.images as Record<string, string>,
      true,
    );
  }

  /**
   * Builds the plan and checks every asset it reads belongs to this workspace
   * and is a raster image (or a font file), within size limits. Returns a
   * loader bound to exactly those checked assets.
   */
  private async verifyPlan(
    scope: Scope,
    layout: TemplateLayout,
    formatKey: string,
    brand: BrandContext | null,
    values: Record<string, string>,
    images: Record<string, string>,
    _forRender: boolean,
  ): Promise<{
    plan: RenderPlan;
    loader: { loadImage(id: string): Promise<Buffer>; loadFont(id: string): Promise<Buffer> };
    versions: Record<string, string>;
  }> {
    if (!getDesignFormat(formatKey))
      throw new UnprocessableEntityException(`Unknown format "${formatKey}".`);
    let plan: RenderPlan;
    try {
      plan = buildRenderPlan({ layout, formatKey, brand, values, images });
    } catch (error) {
      this.invalid(error);
    }
    const fontIds = new Set(
      [
        brand?.kit?.typography.heading?.fontAssetId,
        brand?.kit?.typography.body?.fontAssetId,
      ].filter((id): id is string => Boolean(id)),
    );
    const assets = plan.assetIds.length
      ? await this.prisma.client.mediaAsset.findMany({
          where: { ...scope, id: { in: plan.assetIds } },
          select: { id: true, storageKey: true, mimeType: true, sizeBytes: true, createdAt: true },
        })
      : [];
    const byId = new Map(assets.map((asset) => [asset.id, asset]));
    const versions: Record<string, string> = {};
    for (const id of plan.assetIds) {
      const asset = byId.get(id);
      // Missing and foreign look the same.
      if (!asset)
        throw new UnprocessableEntityException(
          'A referenced image, logo or font is not a media asset in this workspace.',
        );
      assertKeyWithinTenant(asset.storageKey, scope);
      if (fontIds.has(id)) {
        if (!FONT_MIME_TYPES.has(asset.mimeType) || asset.sizeBytes > MAX_FONT_BYTES) {
          throw new UnprocessableEntityException(
            'A brand font must be a TTF or OTF file of at most 5 MB.',
          );
        }
      } else if (!IMAGE_MIME_TYPES.has(asset.mimeType) || asset.sizeBytes > MAX_IMAGE_BYTES) {
        throw new UnprocessableEntityException(
          'Design images and logos must be PNG, JPEG or WebP files of at most 25 MB (SVG is not rendered).',
        );
      }
      versions[id] = `${asset.sizeBytes}:${asset.createdAt.toISOString()}`;
    }
    const cache = new Map<string, Promise<Buffer>>();
    const load = (id: string) => {
      const asset = byId.get(id);
      if (!asset)
        return Promise.reject(
          new UnprocessableEntityException('Asset not available to this render.'),
        );
      let pending = cache.get(id);
      if (!pending) {
        pending = this.storage.getObject(asset.storageKey);
        cache.set(id, pending);
      }
      return pending;
    };
    return { plan, loader: { loadImage: load, loadFont: load }, versions };
  }

  private async renderPage(
    plan: RenderPlan,
    pageIndex: number,
    output: { format: 'png' | 'jpeg'; quality: number; maxWidth?: number | null },
    loader: { loadImage(id: string): Promise<Buffer>; loadFont(id: string): Promise<Buffer> },
  ) {
    try {
      return await this.renderer.renderPage(plan, pageIndex, output, loader);
    } catch (error) {
      if (error instanceof DesignRenderError) throw new UnprocessableEntityException(error.message);
      throw error;
    }
  }
}
